version: '3.8'

services:
  # 1. 数据库
  db:
    image: postgres:16-alpine # 官方镜像 alpine 版本体积更小
    container_name: tracker-db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data # 数据持久化，容器删了数据还在
      - ./db/migrations/001_init_schema.sql:/docker-entrypoint-initdb.d/01_init.sql # 挂载建表语句
      - ./db/seeds/001_demo_data.sql:/docker-entrypoint-initdb.d/02_seed.sql # 挂载演示数据
    networks:
      - tracker-network

  # 后端
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: tracker-backend-run
    depends_on:
      - db # 依赖数据库
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

    networks:
      - tracker-network

  # 前端
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: tracker-frontend-run
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - tracker-network

  # 测试运行器
  tests:
    image: drogonframework/drogon:latest
    container_name: tracker-tests-run
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - tracker-network
    entrypoint: >
      sh -c "
      apt-get update && apt-get install -y libargon2-dev gettext-base &&
      envsubst < config/config.template.json > config/config.dev.json &&
      cmake -S . -B docker-build-debug -DCMAKE_BUILD_TYPE=Debug &&
      cmake --build docker-build-debug &&
      cd docker-build-debug &&
      ctest --output-on-failure
      "


# 定义“电话线”（网络）
networks:
  tracker-network:
    driver: bridge

# 定义“硬盘” （卷）
volumes:
  postgres_data:
