#pragma once

#include "modules/project/dto/command/CreateProjectInput.h"
#include "modules/project/dto/command/DeleteProjectInput.h"
#include "modules/project/dto/command/ListProjectOwnerCandidatesInput.h"
#include "modules/project/dto/command/ProjectStatusActionInput.h"
#include "modules/project/dto/command/TransferProjectOwnerInput.h"
#include "modules/project/dto/command/UpdateProjectBasicInfoInput.h"
#include "modules/project/dto/view/CreatedProjectView.h"
#include "modules/project/dto/view/ProjectDetailView.h"
#include "modules/project/dto/view/ProjectListItemView.h"
#include "modules/project/dto/view/ProjectOwnerCandidateView.h"
#include "modules/project/dto/view/TransferredProjectOwnerView.h"
#include "modules/project/dto/view/UpdatedProjectBasicInfoView.h"
#include "modules/project/dto/view/UpdatedProjectStatusView.h"
