#pragma once

#include "modules/task/dto/command/CreateTaskInput.h"
#include "modules/task/dto/command/DeleteTaskInput.h"
#include "modules/task/dto/command/StartTaskInput.h"
#include "modules/task/dto/command/TaskStatusActionInput.h"
#include "modules/task/dto/command/UpdateTaskBasicInfoInput.h"
#include "modules/task/dto/view/CreatedTaskView.h"
#include "modules/task/dto/view/MyTaskListItemView.h"
#include "modules/task/dto/view/StartedTaskView.h"
#include "modules/task/dto/view/TaskDetailView.h"
#include "modules/task/dto/view/TaskListItemView.h"
#include "modules/task/dto/view/TaskProgressRecordView.h"
#include "modules/task/dto/view/UpdatedTaskStatusView.h"
#include "modules/task/dto/view/UpdatedTaskBasicInfoView.h"
