import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'

describe('theme typography tokens', () => {
  it('uses stronger text contrast and heavier default typography across themes', () => {
    const themeSource = readFileSync(resolve(process.cwd(), 'src/styles/theme.css'), 'utf8')
    const baseSource = readFileSync(resolve(process.cwd(), 'src/styles/base.css'), 'utf8')

    expect(themeSource).toContain('--panel-bg: #f3f7fc;')
    expect(themeSource).toContain('--glass-bg-strong: rgba(239, 245, 252, 0.9);')
    expect(themeSource).toContain('--text-main: #102038;')
    expect(themeSource).toContain('--text-soft: #344963;')
    expect(themeSource).toContain('--app-bg: #060916;')
    expect(themeSource).toContain('--panel-bg: #0d1323;')
    expect(themeSource).toContain('--text-main: #ecf3ff;')
    expect(themeSource).toContain('--text-soft: #93a6c7;')
    expect(themeSource).toContain('--accent-start: #7cd3ff;')
    expect(themeSource).toContain('--accent-end: #8d78ff;')
    expect(themeSource).toContain('--accent-tertiary: #d9abff;')
    expect(themeSource).not.toContain('repeating-linear-gradient(')
    expect(themeSource).not.toContain('animation: scanline-drift')
    expect(themeSource).not.toContain('--panel-bg: #ffffff;')
    expect(themeSource).not.toContain('--glass-bg-strong: rgba(255, 255, 255, 0.92);')

    expect(baseSource).toContain("family=Noto+Sans+SC:wght@400;500;600;700")
    expect(baseSource).toContain('line-height: 1.55;')
    expect(baseSource).toContain('font-size: 15px;')
    expect(baseSource).toContain('font-weight: 500;')
    expect(baseSource).toContain('font-weight: 700;')
    expect(baseSource).toContain("font-family: 'Noto Sans SC', 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', 'Segoe UI', sans-serif;")
    expect(baseSource).toContain('font-synthesis: weight style;')
  })

  it('defines a shared semantic work-status palette with blue active states in both themes', () => {
    const themeSource = readFileSync(resolve(process.cwd(), 'src/styles/theme.css'), 'utf8')

    expect(themeSource).toContain('--work-status-pending-color:')
    expect(themeSource).toContain('--work-status-active-color: #0a66ff;')
    expect(themeSource).toContain('--work-status-pending-bg: color-mix(in srgb, var(--accent-neutral) 18%, #f7fbff);')
    expect(themeSource).toContain('--work-status-active-bg: color-mix(in srgb, var(--work-status-active-color) 18%, #f7fbff);')
    expect(themeSource).toContain('--work-status-done-bg: color-mix(in srgb, var(--accent-success) 18%, #f7fbff);')
    expect(themeSource).toContain('--work-status-delayed-bg: color-mix(in srgb, var(--accent-warning) 18%, #fff6ea);')
    expect(themeSource).toContain('--work-status-done-color: var(--accent-success);')
    expect(themeSource).toContain('--work-status-delayed-color: var(--accent-warning);')
    expect(themeSource).toContain('--work-status-active-strong: #0a66ff;')
    expect(themeSource).toContain('--work-status-active-color: #67b7ff;')
    expect(themeSource).toContain('--work-status-pending-bg: color-mix(in srgb, #a6b3cb 20%, var(--panel-bg));')
    expect(themeSource).toContain('--work-status-active-bg: color-mix(in srgb, var(--work-status-active-color) 20%, var(--panel-bg));')
    expect(themeSource).toContain('--work-status-done-bg: color-mix(in srgb, var(--accent-success) 20%, var(--panel-bg));')
    expect(themeSource).toContain('--work-status-delayed-bg: color-mix(in srgb, var(--accent-warning) 20%, var(--panel-bg));')
    expect(themeSource).toContain('--work-status-active-strong: #67b7ff;')
    expect(themeSource).not.toContain('--work-status-pending-bg: color-mix(in srgb, var(--accent-neutral) 14%, transparent);')
    expect(themeSource).not.toContain('--work-status-active-bg: color-mix(in srgb, var(--work-status-active-color) 16%, transparent);')
    expect(themeSource).not.toContain('--work-status-done-bg: color-mix(in srgb, var(--accent-success) 16%, transparent);')
    expect(themeSource).not.toContain('--work-status-delayed-bg: color-mix(in srgb, var(--accent-warning) 16%, transparent);')
    expect(themeSource).not.toContain('--work-status-pending-bg: color-mix(in srgb, #a6b3cb 16%, transparent);')
    expect(themeSource).not.toContain('--work-status-active-bg: color-mix(in srgb, var(--work-status-active-color) 18%, transparent);')
    expect(themeSource).not.toContain('--work-status-done-bg: color-mix(in srgb, var(--accent-success) 18%, transparent);')
    expect(themeSource).not.toContain('--work-status-delayed-bg: color-mix(in srgb, var(--accent-warning) 18%, transparent);')
  })

  it('uses the relocated night sky photo as the global dark background', () => {
    const themeSource = readFileSync(resolve(process.cwd(), 'src/styles/theme.css'), 'utf8')

    expect(existsSync(resolve(process.cwd(), 'src/assets/backgrounds/night-sky.jpg'))).toBe(true)
    expect(themeSource).toContain('html.dark body::before {')
    expect(themeSource).toContain('html.dark body {')
    expect(themeSource).toContain('background-color: #02050d;')
    expect(themeSource).toContain('background: none;')
    expect(themeSource).not.toContain("url('../assets/backgrounds/night-sky.jpg')")
  })

  it('does not keep unused shell tokens or abandoned global surface helper classes', () => {
    const themeSource = readFileSync(resolve(process.cwd(), 'src/styles/theme.css'), 'utf8')

    expect(themeSource).not.toContain('--app-bg-elevated:')
    expect(themeSource).not.toContain('--sidebar-bg:')
    expect(themeSource).not.toContain('--border-strong:')
    expect(themeSource).not.toContain('--shadow-glass:')
    expect(themeSource).not.toContain('--work-status-unknown-contrast:')
    expect(themeSource).not.toContain('.glass-panel {')
    expect(themeSource).not.toContain('.surface-panel {')
    expect(themeSource).not.toContain('html.dark .glass-panel,')
  })
})
